name: Enabling Google APIs
on:
  push:
    branches: [ main ]
    paths:
      - 'google-apis/**'
      - '.github/workflows/setup-apis.yml'

jobs:
  api-enabling:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: google-apis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Restore Terraform state from cache
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: |
            google-apis/terraform.tfstate
            google-apis/terraform.tfstate.backup
          key: ${{ runner.os }}-terraform-${{ hashFiles('google-apis/google-apis.tf') }}
      - name: Print github workspace
        run: |
          echo $GITHUB_WORKSPACE
          pwd
          ls -la $GITHUB_WORKSPACE
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Setup GCP Credentials
        run: |
          echo '${{ secrets.GCP_ACCESS }}' > quadsci-access.json
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Import
        if: ${{ vars.IMPORT == 'true' }}
        run: |
          chmod +x ./import
          ./import
      - name: Terraform Plan
        run: terraform plan -var-file=google-apis.tfvars.json
      - name: Terraform Apply
        run: terraform apply -var-file=google-apis.tfvars.json -auto-approve
      - name: Always cache Terraform state
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            google-apis/terraform.tfstate
            google-apis/terraform.tfstate.backup
          key: ${{ runner.os }}-terraform-${{ hashFiles('google-apis/google-apis.tf') }}


